"""Add KYC column

Revision ID: 287a8a0e402c
Revises: e438ac3f6585
Create Date: 2022-03-21 02:27:52.233527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287a8a0e402c'
down_revision = 'e438ac3f6585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('kyc_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kyc_verified')
    # ### end Alembic commands ###
