"""Add Password reset hash

Revision ID: f5d5d5ea61fa
Revises: 287a8a0e402c
Create Date: 2022-04-13 03:56:41.291513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d5d5ea61fa'
down_revision = '287a8a0e402c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_reset_hash')
    # ### end Alembic commands ###
